# docker/Dockerfile.worker
FROM python:3.13-slim

ENV DEBIAN_FRONTEND=noninteractive \
    RUNNING_IN_DOCKER=1 \
    GOPATH=/root/go \
    PATH="/root/go/bin:/usr/local/go/bin:${PATH}"

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates curl gnupg wget git build-essential libpq-dev \
        masscan nmap sqlmap \
    && rm -rf /var/lib/apt/lists/*

ENV GO_VERSION=1.23.4
RUN curl -fsSL https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz -o /tmp/go.tar.gz \
    && tar -C /usr/local -xzf /tmp/go.tar.gz \
    && rm /tmp/go.tar.gz

RUN go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest \
    && go install -v github.com/projectdiscovery/katana/cmd/katana@latest \
    && go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest \
    && go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest \
    && go install -v github.com/ffuf/ffuf/v2@latest \
    && go install -v github.com/hahwul/dalfox/v2@latest \
    && go install -v github.com/sensepost/gowitness@latest \
    && go install -v github.com/owasp-amass/amass/v4/...@master

RUN curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh \
    | sh -s -- -b /usr/local/bin

RUN nuclei -update-templates -silent || true

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV HTTPX_GO_BINARY=/root/go/bin/httpx

CMD ["celery", "-A", "worker.celery.celery_app", "worker", "--loglevel=info"]
