"""initial schema

Revision ID: 51fcc0baf9ea
Revises: 
Create Date: 2026-07-02 00:45:41.551201

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '51fcc0baf9ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'viewer', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'failed', name='scanstatus'), nullable=True),
    sa.Column('current_stage', sa.Enum('asset_discovery', 'recon', 'port_scan', 'live_hosts', 'crawl', 'vuln_scan', 'validation', 'enrichment', 'scoring', 'complete', name='scanstage'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_id'), 'scans', ['id'], unique=False)
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('tech_stack', sa.String(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('screenshot_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_id'), 'endpoints', ['id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('kev_status', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('patch_recommendation', sa.String(), nullable=True),
    sa.Column('fix_version', sa.String(), nullable=True),
    sa.Column('is_false_positive', sa.Boolean(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_cve_id'), 'findings', ['cve_id'], unique=False)
    op.create_index(op.f('ix_findings_id'), 'findings', ['id'], unique=False)
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port_number', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ports_id'), 'ports', ['id'], unique=False)
    op.create_table('subdomains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subdomains_id'), 'subdomains', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subdomains_id'), table_name='subdomains')
    op.drop_table('subdomains')
    op.drop_index(op.f('ix_ports_id'), table_name='ports')
    op.drop_table('ports')
    op.drop_index(op.f('ix_findings_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_cve_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_endpoints_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_scans_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
