"""add scanners field to scan

Revision ID: 902f6ebb94f9
Revises: 51fcc0baf9ea
Create Date: 2026-07-03 17:45:02.536706

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '902f6ebb94f9'
down_revision: Union[str, None] = '51fcc0baf9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('scanners', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'scanners')
    # ### end Alembic commands ###
