"""add emails_found to scan

Revision ID: ab396a6407b4
Revises: c44a6ef30023
Create Date: 2026-07-07 12:59:39.096501

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ab396a6407b4'
down_revision: Union[str, None] = 'c44a6ef30023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('emails_found', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'emails_found')
    # ### end Alembic commands ###
