"""add task_id to scan

Revision ID: c44a6ef30023
Revises: 902f6ebb94f9
Create Date: 2026-07-06 11:25:56.452164

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c44a6ef30023'
down_revision: Union[str, None] = '902f6ebb94f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'task_id')
    # ### end Alembic commands ###
